### PR TITLE
Update SuperCollider.download code signature

### PR DESCRIPTION
**Pull request by dcoobs**

### CODE REVIEW

**Comment by dcoobs** [comment]
I believe failures are simply due to trust info

**Comment by dcoobs** [comment]
Oops accidentally closed. Reopening PR

**Comment by macmule** [comment]
Bump :)

**Comment by neilmartin83** [comment]
Bump

**Comment by orbsmiv** [comment]
Argh... many apologies for the delay – I've not been checking my PRs enough recently :-/
Merging now!

**Pull request merged**
